# Generated by Django 5.1.3 on 2024-11-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
